#!/usr/bin/env bash
# script that configures a new Ubuntu machine
sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo /etc/init.d/nginx restart

sudo rm /var/www/html/*.html
sudo echo 'Hello World\n' | sudo tee /var/www/html/index.html
