#!/usr/bin/env bash
# script that configures a new Ubuntu machine
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chmod 777 /var/www/html/index.html
sudo echo "Hello World" |sudo tee /var/www/html/index.html