#!/usr/bin/env bash
# script that configures a new Ubuntu machine
sudo apt-get -y update
sudo apt-get -y install nginx
sudo chmod 777 /var/www/html/index.nginx-debian.html
sudo echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo service nginx restart