#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page
sudo apt-get -y update
sudo apt-get install -y nginx
sudo rm /var/www/html/*.html
sudo echo 'Hello World' | sudo tee /var/www/html/index.html
redir="\tlocation /redirect_me {\n\t\treturn 301 \@scheme://youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\tlocation / {"
sudo sed -i "s|$replace|$redir|" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
