#!/usr/bin/env bash
# Install Nginx that its HTTP response contains a custom header
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "H" > /var/www/html/index.nginx-debian.html
sed -i "s/server_name _;/server_name _;\n \tlocation /redirect_me {\n \t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n/" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sed -i "s/server_name _;/server_name _;\n \terror_page 404 /custom_404.html;\n/" /etc/nginx/sites-available/default
sed -i "s/location \/ {/location \/{\n \t\tadd_header X-Served-By '${HOSTNAME}';\n/" /etc/nginx/sites-available/default
service nginx start